### ISSUE TITLE
rails3でのnot inのスコープを作りたい

### ISSUE THREAD

**Issue by kazuhisa** [hayashima/kakurenbo-puti#1]
@MnrUchida 
SQLの魔術師にお聞きしたいことがあります。
Rails4用のkakurenbo-putiをRails3で動くように修正してるんだけど、scopeの設定がうまく書けずに困っています。
https://github.com/hayashima/kakurenbo-puti/blob/rails3/lib/kakurenbo_puti/active_record_base.rb#L41-L56
問題はここの`only_soft_destroyed`ってスコープを定義しているところです。
ActiveRecord4のmasterブランチで動かすとonly_soft_destroyedは次のようなSQLになります。

``` SQL
SELECT "soft_delete_children".* FROM "soft_delete_children" WHERE ("soft_delete_children"."id" NOT IN (
SELECT "soft_delete_children"."id" FROM "soft_delete_children" INNER JOIN "soft_delete_models" ON "soft_delete_models"."id" = "soft_delete_children"."soft_delete_model_id" INNER JOIN "normal_models" ON "normal_models"."id" = "soft_delete_children"."normal_model_id" WHERE "soft_delete_children"."soft_destroyed_at" IS NULL AND "soft_delete_models"."soft_destroyed_at" IS NULL))
```

ActiveRecord3のrails3ブランチでも同様に`without_soft_destroyed.select(:id)`の結果をnot in idにうまく指定できればRails3でも動くと思っています。
どうやって指定すればいいでしょうか？

`bundle exec rspec`で動作検証はできると思うので、見てみてもらえないでしょうか？

**Comment by MnrUchida** [comment]
@kazuhisa 
SQL、またはarelで記述するのが妥当かと思います。
一応、下のパターンでrspecが通ることは確認できました。

```
# SQLで記述するパターン
scope :only_soft_destroyed, -> { where("#{self.table_name}.id not in (#{without_soft_destroyed.select("#{self.table_name}.id").to_sql})") }

# arelで記述するパターン
scope :only_soft_destroyed, -> { where(self.arel_table[:id].not_in(without_soft_destroyed.select(self.arel_table[:id]).arel)) }
```

**Comment by kazuhisa** [comment]
@MnrUchida 
素晴らしい！僕もArelを使うパターンと似たようなことを試行錯誤してたんだけど、結局良く分からなかった...
ありがとう！
